title: TIMWANG.ME
email: tim.wangyao@gmail.com
description: >-
  Frontend Developer
  / Working in Shanghai
  / React Native Collaborators
  / TypeScript Enthusiasts
  / React / NodeJS / DevOps
baseurl: ""
url: "https://timwang.me"
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
