title: TIMWANG.ME
author: Tim Wang
email: tim.wangyao@gmail.com
description: >
  Frontend Developer
  / Shanghai
  / React Native Collaborators
  / TypeScript Enthusiasts
  / React / NodeJS / DevOps
baseurl: ""
url: "https://timwang.me"
twitter_username: jekyllrb
github_username:  jekyll
rss: rss

theme: minima

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

header_pages:
- about.md

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
